name: Generate Space Invaders

on:
  schedule:
    - cron: "0 */24 * * *" # once a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate animation
        uses: Platane/snk@v3
        with:
          github_user_name: yash-144
          outputs: |
            dist/space-invaders.svg
            dist/space-invaders.gif

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}